before_install:
- openssl aes-256-cbc -K $encrypted_99b47944e939_key -iv $encrypted_99b47944e939_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 400 ~/.ssh/deploy_rsa
- chmod +x push.sh

jobs:
  include:
  - stage: Push
    script:
    - "./push.sh"
