version: '3.5'

services:
  laravel-app:
    build:
      context: './Dashboard'
      args:
        uid: 1000
    depends_on:
      - mysql-db
    container_name: laravel-app
    environment:
      - APP_NAME=Dashboard
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - DB_HOST=mysql-db
      - DB_DATABASE=db
      - DB_PASSWORD=securerootpassword
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - db

  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: securerootpassword 
    networks:
      backend:
        aliases:
          - myadmin

networks:
  backend:
    name: backend-network
